-- Tabela de Visitas do JP
CREATE TABLE visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  data DATE NOT NULL, -- dd/mm/yyyy será convertido para yyyy-mm-dd no insert
  dia_da_semana TEXT,
  consultor TEXT NOT NULL,
  cliente TEXT,
  loja TEXT NOT NULL,
  check_in TEXT,
  check_out TEXT,
  cnpj TEXT,
  nome_pdv TEXT
);

-- Habilitar RLS (Segurança) mas deixar aberto por enquanto
ALTER TABLE visits ENABLE ROW LEVEL SECURITY;

-- Política para todos lerem e escreverem (Simplificado conforme necessidade)
CREATE POLICY "Acesso Público" ON visits FOR ALL USING (true) WITH CHECK (true);
